language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 2.2.100
before_install:
  - chmod +x ./build.sh
script:
  - ./build.sh --quiet verify
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1