language: csharp
dist: xenial
sudo: required
mono: none
env:
  - MSBUILDDISABLENODEREUSE=1
dotnet: 2.2
script:
  - set MSBUILDDISABLENODEREUSE=1
  - dotnet build /p:Configuration=ReleaseNetCore /p:Platform="Any CPU" --framework netcoreapp2.2 -nodereuse:false  /m:1
  - dotnet test --no-build --configuration ReleaseNetCore --framework netcoreapp2.2 -nodereuse:false  /m:1
