language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 2.2
script:
  - dotnet build /p:Configuration=ReleaseNetCore /p:Platform="Any CPU" --framework netcoreapp2.2 -nodereuse:false
  - dotnet test --no-build --configuration ReleaseNetCore --framework netcoreapp2.2
